# Generated by Django 5.0.1 on 2024-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('banner', 'Banner'), ('interstitial', 'Interstitial'), ('rewarded', 'Rewarded')], max_length=20)),
                ('code', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('package_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('banner', 'Banner'), ('interstitial', 'Interstitial'), ('rewarded', 'Rewarded')], max_length=20)),
                ('content', models.FileField(upload_to='ads/')),
                ('active', models.BooleanField(default=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('package_name', models.CharField(max_length=100)),
            ],
        ),
    ]
