# Generated by Django 5.0.1 on 2024-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customad',
            old_name='content',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='customad',
            name='age',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='customad',
            name='creator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customad',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customad',
            name='downloads',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customad',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customad',
            name='rate',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='customad',
            name='total_rate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
