# Generated by Django 5.0.1 on 2024-02-13 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AD', '0002_rename_content_customad_logo_customad_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/screenshots/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AD.customad')),
            ],
        ),
    ]
