# Generated by Django 5.0.1 on 2024-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='locale',
            field=models.CharField(choices=[('fa_IR', 'Fa Ir'), ('en_US', 'En Us')], default='en_US', max_length=100),
        ),
    ]
